Sl_Processo/Sl_Processo/Controllers/ProcessoController.cs
using Sl_Processo.Repositorio;
using Sl_Processo.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Sl_Processo.Filters;
using Sl_Processo.Models.ValueObjects;
using DotNet.Highcharts;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using System.Drawing;
using Point = DotNet.Highcharts.Options.Point;

namespace Sl_Processo.Controllers
{
    [Autenticacao]
    public class ProcessoController : Controller
    {
        ProcessoRepositorio rProcesso = new ProcessoRepositorio();
        MovimentoProcessoRepositorio rMovimentoProcesso = new MovimentoProcessoRepositorio();
        ControleDeProcessosRepositorio rControleProcesso = new ControleDeProcessosRepositorio();
        EmpresaParticipanteRepositorio rParticipante = new EmpresaParticipanteRepositorio();
        UnidadeInternaRepositorio rUnidadeInterna = new UnidadeInternaRepositorio();

        int codSetor = 0;

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ConsultaProcessosDoParticipante()
        {
            //ViewBag.CodParticipante = new SelectList(rParticipante.BuscarTodos(), "CodParticipante", "RazaoSocial");
            return View();
        }
        public ActionResult ProcessosDoParticipante(int codParticipante)
        {
            var objParticipante = rParticipante.BuscarParticipantePorCodigo(codParticipante);
            ViewBag.participanteCnpj = objParticipante.CNPJFormatado;
            ViewBag.participanteNome = objParticipante.RazaoSocial;
            return View(rProcesso.BuscarProcessosDoParticipanteNoPeriodo(codParticipante));
        }
        public ActionResult Historico(TB_Processo processo)
        {
            if (string.IsNullOrEmpty(processo.NumeroProcesso) && string.IsNullOrEmpty(processo.Objeto))
            {
                ViewBag.setClass = "alert alert-danger";
                ViewBag.message = "Atenção !!! Informe pelo menos um parâmetro para a pesquisa";
                return View("Index");
            }

            try
            {
                var numeroProcesso = processo.NumeroProcesso;
                var objetoProcesso = processo.Objeto == null ? string.Empty : processo.Objeto;

                if (objetoProcesso.Length > 0)
                {
                    return RedirectToAction("ListaDeProcessosPorAssunto", processo);
                }
                var objProcesso = rProcesso.BuscarProcessoPorNumeroProcesso(processo);

                return View(objProcesso);
            }
            catch (Exception)
            {
                ViewBag.ProcessoNaoLocalizado = "Número de Processo Não Localizado!";
                return View("Index");
            }
           
        }
        public ActionResult ListaDeProcessosPorAssunto(TB_Processo processo)
        {
            var lista = rProcesso.BuscarProcessoPorAssunto(processo);
            return View(lista);
        }
        public ActionResult PrazosEquipes()
        {
            codSetor = Convert.ToInt32(Session["codUndInterna"]);
            ViewBag.Setor = codSetor;

            ViewBag.Anos = new SelectList(ListaAnos(), "value", "Text");

            if (Administrador(codSetor))
            {
                ViewBag.CodUnidadeInterna = new SelectList(rProcesso.ListaEquipes(), "CodUnidadeInterna", "NomeUnidadeInterna");
            }
            else
            {
                ViewBag.CodUnidadeInterna = new SelectList(rProcesso.BuscarUnidadePorId(codSetor), "CodUnidadeInterna", "NomeUnidadeInterna", codSetor);
            }
            ViewBag.CodDescricaoMovimento = new SelectList(rProcesso.ListaDescricaoMovimentacao(), "CodDescricaoMovimento", "DescricaoMovimento");
            return View();
        }
        [HttpPost]
        public ActionResult ListaPrazosDaEquipe(ProcessoVO pesquisa)
        {
            int codSetor = Convert.ToInt32(Session["codUndInterna"]);

            if (!Administrador(codSetor))
            {
                pesquisa.Equipe = Convert.ToInt32(Session["codUndInterna"]);
            }

            var prazos = rControleProcesso.ListaPrazosPorEquipe(pesquisa);

            ViewBag.Equipe = pesquisa.Equipe == 0 ? "Todas as unidades" : rUnidadeInterna.BuscaUnidadeInterna(pesquisa.Equipe).NomeUnidadeInterna;

            ViewBag.ExibirGrafico = false;

            if (prazos.Count > 0)
            {
                GraficoPrazosEquipe(pesquisa);
                ViewBag.ExibirGrafico = true;
            }

            return View(prazos);
        }
        public ActionResult PartialListaPrazosDaEquipe()
        {
            IEnumerable<VW_CotroleDeProcessos> lista = new List<VW_CotroleDeProcessos>();
            return View(lista);
        }
        [HttpPost]
        public ActionResult PartialListaPrazosDaEquipe(ProcessoVO pesquisa)
        {
            var lista = rControleProcesso.ListaPrazosPorEquipe(pesquisa);
            return PartialView(lista);
        }
        public ActionResult PrazoGeral()
        {
            int[] totais = new ControleDeProcessosRepositorio().ListaPrazosGeral();
            return View(Chart(totais, "Situação dos Processos Referente aos Prazos"));
        }
        public ActionResult GraficoPrazosEquipe(ProcessoVO pesquisa)
        {
            var lista = rControleProcesso.ListaPrazosPorEquipe(pesquisa);

            int atrasado = 0;
            int quaseNoPrazo = 0;
            int noPrazo = 0;
            int total = 0;

            foreach (var item in lista)
            {

                if (item.TotalDias > item.LimiteDeDias)
                {
                    atrasado++;
                }
                else if ((item.TotalDias + 7) > item.LimiteDeDias)
                {
                    quaseNoPrazo++;
                }
                else
                {
                    noPrazo++;
                }

            }

            total = atrasado + quaseNoPrazo + noPrazo;
            int[] totais = new int[4];
            totais[0] = atrasado;
            totais[1] = quaseNoPrazo;
            totais[2] = noPrazo;
            totais[3] = total;

            Highcharts grafico = ChartEquipe(totais, "Processos da Equipe");

            return View(grafico);

        }
        protected Highcharts Chart(int[] totais, string titulo)
        {

            ViewBag.Totais = totais;
            Highcharts chart = new Highcharts("chart")                
                .InitChart(new Chart
                {                    
                    Type = ChartTypes.Pie,
                    MarginTop = 80,
                    MarginRight = 40,
                    Options3d = new ChartOptions3d
                    {
                        Enabled = true,
                        Alpha = 45,
                        Beta = 0
                    }
                })
                .SetOptions(new GlobalOptions
                {
                    Colors = new[]
                                         {
                                             ColorTranslator.FromHtml("#b84d45"),
                                             ColorTranslator.FromHtml("#f0ad4e"),
                                             ColorTranslator.FromHtml("#5cb85c"),
                                             ColorTranslator.FromHtml("#7CB5EC")
                                         }
                })
                .SetTitle(new Title { Text = titulo })
                .SetTooltip(new Tooltip { PointFormat = "{series.name}: <b>{point.percentage:.1f}%</b>" })
                .SetPlotOptions(new PlotOptions
                {
                    Pie = new PlotOptionsPie
                    {                      
                        AllowPointSelect = true,
                        Cursor = Cursors.Pointer,
                        Depth = 35,
                        DataLabels = new PlotOptionsPieDataLabels
                        {
                            Enabled = true,
                            Format = "{point.name}"
                        }

                    }
                })
                .SetSeries(new Series
                {
                    Type = ChartTypes.Pie,
                    Name = "Prazos",
                    Data = new Data(new object[]
                    {
                        new object[] { "Atrasados", totais[0] },
                        new object[] { "Chegando no Prazo", totais[1] },
                        new Point
                        {
                            Name = "No Prazo",
                            Y = totais[2],
                            Sliced = true,
                            Selected = true
                        },
                        new object[] { "Concluidos", totais[3] }
                    })
                });
            return chart;
        }
        protected Highcharts ChartEquipe(int[] totais, string titulo)
        {

            ViewBag.Totais = totais;
            Highcharts chart = new Highcharts("chart")
                .InitChart(new Chart
                {
                    Type = ChartTypes.Pie,
                    MarginTop = 80,
                    MarginRight = 40,
                    Options3d = new ChartOptions3d
                    {
                        Enabled = true,
                        Alpha = 45,
                        Beta = 0
                    }
                })
                .SetOptions(new GlobalOptions
                {
                    Colors = new[]
                                         {
                                             ColorTranslator.FromHtml("#b84d45"),                                             
                                             ColorTranslator.FromHtml("#f0ad4e"),
                                             ColorTranslator.FromHtml("#5cb85c")                                             
                                         }
                })

Sl_Processo/Sl_Processo/Views/Processo/ConsultaProcessosDoParticipante.cshtml
@model Sl_Processo.Models.ValueObjects.ProcessoVO

@{
    ViewBag.Title = "ConsultaProcessosDoParticipante";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
<br />
<br />
<div class="container">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Informe a Empresa Participante</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group col-md-3">
                <label class="control-label">CNPJ</label>
                @Html.TextBoxFor(model => model.CnpjParticipante, new { @class = "form-control cnpj" })
                @Html.ValidationMessageFor(model => model.CnpjParticipante, "", new { @class = "text-danger" })
            </div>            
            <div class="row col-md-6">
                <div class="form-group col-md-5">
                    <label class="control-label">Data Início</label>
                    @Html.TextBoxFor(model => model.PeriodoInicio, new { @class = "form-control data-pt-br" })
                    @Html.ValidationMessageFor(model => model.PeriodoInicio, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-5">
                    <label class="control-label">Data Fim</label>
                    @Html.TextBoxFor(model => model.PeriodoFim, new { @class = "form-control data-pt-br" })
                    @Html.ValidationMessageFor(model => model.PeriodoFim, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Consultar" class="btn btn-infor" />
                </div>
            </div>
        </div>
    }

</div>

@section scripts{
    <script src="~/Scripts/jquery.maskedinput.js"></script>
    <script>
        $(function () {
            $(".cnpj").mask("99.999.999/9999-99", { placeholder: "00.000.000/0000-00" });
            $(".data-pt-br").mask("99/99/9999", { placeholder: "99/99/9999" });
        });
    </script>
}

Sl_Processo/Sl_Processo/Views/Processo/Destaque.cshtml
@model IEnumerable<Sl_Processo.Models.TB_Processo>

@{
    ViewBag.Title = "Destaque";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <h3>Processos em Destaque</h3>
    </div>
    <div class="row">
        @Html.ActionLink("Voltar", "IndexRelatorios", "Home", null, new { @Class = "btn btn-info" })
        <hr />
    </div>
   
    <div class="row">
        <table class="table table-bordered table-responsive">
            <tr>
                <th>
                    Número do Processo
                </th>
                <th>
                    Objeto
                </th>

              
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a href="@Url.Content("~/Processo/BuscaProcessoDestaque?id=" + item.NumeroProcesso)" class="btn btn-info"> @Html.DisplayFor(modelItem => item.NumeroProcesso)</a>
</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Objeto)
                    </td>
                  
                </tr>
            }

        </table>
    </div>
</div>

Sl_Processo/Sl_Processo/Views/Processo/GraficoPrazosEquipe.cshtml
@{Layout = null;}
@model DotNet.Highcharts.Highcharts
<link href="~/Content/Highcharts-theme/jquery-ui-1.10.3.custom.min.css" rel="stylesheet" />
<link href="~/Scripts/google-code-prettify/prettify.css" rel="stylesheet" />

<script src="~/Scripts/jquery-2.0.0.min.js"></script>
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/jquery-ui-1.10.3.min.js"></script>
<script src="~/Scripts/Highcharts-4.0.1/js/highcharts-all.js"></script>
<script src="~/Scripts/Highcharts-4.0.1/js/highcharts.js"></script>
<script src="~/Scripts/Highcharts-4.0.1/js/modules/funnel.js"></script>

<script src="~/Scripts/google-code-prettify/prettify.js"></script>

<br />
<br />

<div class="container">
    <div class="prettyprint()">
        @(Model)
    </div>
</div>

Sl_Processo/Sl_Processo/Views/Processo/Historico.cshtml
@{
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
    ViewBag.Title = "Historico";
    int dias = 0;
    DateTime dataAnt = DateTime.Now;
    int pos = 0;
}
<link href="~/Content/datatable1/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/datatables.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/responsive.bootstrap.min.css" rel="stylesheet" />

<style>
    body, table {
        font-size: .99em !important;
    }
</style>
@model Sl_Processo.Models.TB_Processo
<div class="container-fluid">
    @Html.ActionLink("Voltar", "Index", "Processo", new { @Class = "btn btn-info" })
    <hr />
    <div class="alert alert-info">
        <h4 class="visible-lg visible-md">Histórico de movimentação do processo : <strong>@Model.NumeroProcesso</strong></h4>
        <h5 class="visible-sm">Histórico de movimentação do processo : <strong>@Model.NumeroProcesso</strong></h5>
        <h6 class="visible-xs">Histórico de movimentação do processo : <strong>@Model.NumeroProcesso</strong></h6>
    </div>
    <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered" cellspacing="0">
            <thead>
                <tr>
                    <th>Data Movimento</th>
                    <th class="hidden-xs">Usuário</th>
                    <th>Origem</th>
                    <th>Destino</th>
                    <th class="hidden-xs">Observação</th>
                    <th class="">Motivo</th>
                    <th>Dias no setor</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.TB_MovimentoProcesso)
            {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.DataMovimento)</td>
                        <td class="hidden-xs">@Html.DisplayFor(modelItem => item.Usuario)</td>
                        <td>@Html.DisplayFor(modelItem => item.TB_UnidadeInterna.NomeUnidadeInterna)</td>
                        <td>@Html.DisplayFor(modelItem => item.TB_UnidadeInterna1.NomeUnidadeInterna)</td>
                        <td class="hidden-xs">@Html.DisplayFor(modelItem => item.ObservacaoMovimento)</td>
                        <td>@Html.DisplayFor(modelItem => item.TB_DescricaoMovimento.DescricaoMovimento)</td>
                        @if (pos == 0)
                        {
                            dias = 0;

                            <td class="text-center">@dias</td>
                        }
                        else
                        {
                            TimeSpan date = Convert.ToDateTime(dataAnt) - Convert.ToDateTime(item.DataMovimento.ToShortDateString()) ;
                            dias = date.Days;
                            <td class="text-center">@dias</td>
                        }
                    </tr>
                    dataAnt = Convert.ToDateTime(@item.DataMovimento.ToShortDateString());
                    pos = (pos + 1);
                }
            </tbody>
        </table>
    </div>
</div>
@Scripts.Render("~/bundles/datatable1")
<script src="~/Scripts/datatable1/dataTables.responsive.min.js"></script>
<script src="~/Scripts/datatable1/responsive.bootstrap.min.js"></script>

@section Scripts {    
    <script>
        $.extend(true, $.fn.dataTable.defaults, {
            //"searching": false,
            "ordering": false
        });
    </script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "oLanguage": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar nesta tabela",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    }
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            });
        })

    </script>
}

Sl_Processo/Sl_Processo/Views/Processo/Index.cshtml
@model Sl_Processo.Models.TB_Processo

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
    var setClass = @ViewBag.setClass;
}
<script src="~/Scripts/Mascaras.js"></script>
<br />

<div class="@setClass" role="alert">
    <h4><strong>@ViewBag.message</strong></h4>
</div>
<div class="container-fluid">
    @using (Html.BeginForm("Historico", "Processo", FormMethod.Get))
    {
        <div class="panel panel-primary">
            <div class="panel-heading"><h3 class="panel-title">Consulta de Movimentação de Processo</h3></div>
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="panel-body">
                <div class="form-group col-md-3">
                    <label class="control-label">Número do Processo</label>
                    @Html.TextBoxFor(model => model.NumeroProcesso, new { @Class = "form-control", @onkeyup = "mascara(this, processo);", @maxlength = "21" })
                    @ViewBag.ProcessoNaoLocalizado
                </div>

                <div class="form-group col-md-7">
                    <label class="control-label">Objeto :</label>
                    @Html.TextBoxFor(model => model.Objeto, new { @class = "form-control" })
                </div>
            </div>
            <div class="panel-footer">
                <input type="submit" value="Buscar" class="btn btn-primary" />
                @Html.ActionLink("voltar", "IndexRelatorios", "Home", null, new {@Class="btn btn-info" })
            </div>
        </div>
    }
</div>
@section scripts{
    @*<script src="~/Scripts/jquery.maskedinput.js"></script>
    <script>
        $(function () {
            $(".processo").mask("99-9999.99999-99-9999", { placeholder: "00-0000.00000-00-0000" });
        });
    </script>*@
}

Sl_Processo/Sl_Processo/Views/Processo/ListaDeProcessosPorAssunto.cshtml
@model IEnumerable<Sl_Processo.Models.TB_Processo>

@{
    ViewBag.Title = "ProcessosPorAssunto";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
<link href="~/Content/datatable1/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/datatables.min.css" rel="stylesheet" />
<style>
    body {
        font-size: .98em !important;
    }
</style>

@Html.ActionLink("Voltar", "Index", "Processo", new {@Class="btn btn-info" })

    <h4>Processos Por Assunto</h4>
<div class="table-responsive">
    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th><label>Nº Processo</label></th>
                <th><label>Objeto</label></th>
                <th>Data e Hora</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.ActionLink(item.NumeroProcesso, "Historico", "Processo", new { item.NumeroProcesso }, new { @Class = "btn btn-sm btn-info" })</td>
                    <td>@Html.DisplayFor(itemModel => item.Objeto)</td>
                    <td>@Html.DisplayFor(itemModel => item.DataHoraLicitacao)</td>

                </tr>
            }
        </tbody>
    </table>
</div>


@section Scripts {

    @Scripts.Render("~/bundles/datatable1")
    @*<script src="~/Scripts/datatable1/datatables.min.js"></script>*@

    <script>
        $(document).ready(function () {          
           $('#example').DataTable({
                "oLanguage": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar nesta tabela",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    }
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            });
        })
    </script>
}

Sl_Processo/Sl_Processo/Views/Processo/ListaPrazosDaEquipe.cshtml
@model IEnumerable<Sl_Processo.Models.VW_CotroleDeProcessos>

<link href="~/Content/Site.css" rel="stylesheet" />
<link href="~/Content/TableColor.css" rel="stylesheet" />
<style>
    body, table {
        font-size: .99em !important;
    }
</style>

@{
    ViewBag.Title = "ListaPrazosDaEquipe";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
    var mostraGrafico = ViewBag.ExibirGrafico;
    int i = 0;
}

<br />
<div class="container-fluid">
    <button type="button" onclick="history.go(-1)" class="btn btn-info">Voltar</button>
    <div class="row">
        <div class="col-md-12">
            <h3>Lista Prazos para: @ViewBag.Equipe</h3>
        </div>
    </div>

    <div class="row">
        <div class="table-responsive">
            <div>
                <table class="table table-bordered table-hover" width="100%" cellspacing="0">                    
                        <tr>
                            <th><label>Item</label></th>
                            <th><label>Nº do Processo</label></th>
                            <th><label>Objeto</label></th>
                            <th><label>Órgão Interessado</label></th>
                            <th><label>Dt Encaminhamento</label></th>
                            <th><label>Equipe</label></th>
                            <th><label>Prazo em dias</label></th>
                            <th><label>Total de Dias na Equipe</label></th>
                        </tr>
                    
                    
                        @foreach (var item in Model)
                        {
                            string corLinha = string.Empty;


                            if (item.TotalDias > item.LimiteDeDias)
                            {
                                corLinha = "dangerth";
                            }
                            else if ((item.TotalDias + 7) > item.LimiteDeDias)
                            {
                                corLinha = "warningth";
                            }
                            else
                            {
                                corLinha = "successth";
                            }

                            <tr class="@corLinha">
                                <td class="@corLinha">@{i++;}@i</td>
                                <td style="min-width: 13%">@item.NumeroProcesso</td>
                                <td>@Html.DisplayFor(modelItem => item.Objeto)</td>
                                <td>@Html.DisplayFor(modelItem => item.Sigla)</td>
                                <td>@Html.DisplayFor(modelItem => item.DataMovimento)</td>
                                <td>@Html.DisplayFor(modelItem => item.NomeUnidadeInterna)</td>
                                <td class="text-center">@Html.DisplayFor(modelItem => item.LimiteDeDias)</td>
                                <td class="text-center">@Html.DisplayFor(modelItem => item.TotalDias)</td>
                            </tr>
                                    }                    
                </table>
            </div>
        </div>
        @if (mostraGrafico)
        {
            <div class="col-xs-12 hidden-md">
                @Html.Action("GraficoPrazosEquipe")
            </div>
        }
        
    </div>
    <div class="row">
        <div class="col-md-2">
            @Html.ActionLink("Voltar", "PrazosEquipes", "Processo", null, new { @Class = "btn btn-info" })
        </div>
    </div>
</div>

Sl_Processo/Sl_Processo/Views/Processo/PrazosEquipes.cshtml
@model Sl_Processo.Models.ValueObjects.ProcessoVO

    <link href="~/Content/Site.css" rel="stylesheet" />
    @{
        ViewBag.Title = "PrazosEquipes";
        Layout = "~/Views/Shared/_LayoutInterno.cshtml";
    }

    <div class="container-fluid">
        <div class="row">
            <div class="visible-lg col-md-12">
                <h2>Controle de Processo - Pregão Eletrônico e Presencial</h2>
            </div>
            <div class="visible-md col-md-12">
                <h3>Controle de Processo - Pregão Eletrônico e Presencial</h3>
            </div>
            <div class="visible-sm col-sm-12">
                <h4>Controle de Processo - Pregão Eletrônico e Presencial</h4>
            </div>
            <div class="visible-xs col-sm-12">
                <h5>Controle de Processo - Pregão Eletrônico e Presencial</h5>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        @using (Html.BeginForm("ListaPrazosDaEquipe", "Processo", FormMethod.Post))
        {
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <strong> Relatório de Prazos por Equipe</strong>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-2">
                            <label>ANO</label>
                            @Html.DropDownListFor(model => model.Ano, (SelectList)ViewBag.Anos, "Selecione...", new { @Class = "form-control" })
                        </div>  
                         <div class="col-md-3">
                            <label>Equipe</label>
                            @Html.DropDownListFor(model => model.Equipe, (SelectList)ViewBag.CodUnidadeInterna, "Todas Equipes", new { @class = "form-control" })
                        </div>
                        <div class="col-md-4">
                            <label>Assunto</label>
                            @Html.DropDownListFor(model => model.Assunto, (SelectList)ViewBag.CodDescricaoMovimento, "Todos Assuntos", new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <input type="submit" class="btn btn-primary" value="Enviar" />
                    @Html.ActionLink("voltar", "IndexRelatorios", "Home", null, new { @Class = "btn btn-info" })
                </div>
            </div>
        }
    </div>