Sl_Processo/Sl_Processo/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sl_Processo.Models;
using System.Data.SqlClient;
using System.Configuration;
using Sl_Processo.Filters;


namespace Sl_Processo.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly Context model = new Context();
       

        [AllowAnonymous]
        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult PartialLogin()
        {          
          return View();
        }

        [HttpPost]
        public ActionResult Login(string login, string senha)
        {
            var user = Autenticacao.BuscarUsuario(login, senha);

            if (user != null)
            {
                Session["user"] = user;
                Session["username"] = user.nome;
                Session["codUndInterna"] = user.TB_UnidadeInterna.CodUnidadeInterna;
                Session["setorSigla"] = user.TB_UnidadeInterna.NomeUnidadeInterna;

                Session["erroLogin"] = null;

                return RedirectToAction("IndexRelatorios", "Home");
               
            }
            else
            {
                Session["erroLogin"] = "C.P.F ou Senha Inválida!";
                return RedirectToAction("Index");
            }
           
        }
        
        public ActionResult Logoff ()
        {
            Session["user"] = null;
            Session["username"] = null;
            Session["codUndInterna"] = null;
            Session["setorSigla"] = null;
            Session.Abandon();
            return RedirectToAction("Index");
        }       
      
    }
}

Sl_Processo/Sl_Processo/Views/Usuario/Index.cshtml
@{
    ViewBag.Title = "Sistema de Processos - Acesso Restrito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    
    @Html.Action("PartialLogin", "Usuario")
</div>

Sl_Processo/Sl_Processo/Views/Usuario/PartialLogin.cshtml
@model Sl_Processo.Models.TB_Usuarios
@{
    ViewBag.Title = "Sistema de Processos - Acesso Restrito";
    Layout = null;
}
<script src="~/Scripts/Mascaras.js"></script>
<br />
<br />
<div class="container">
    <div class="row topRow">
        <div class="col-md-4 col-md-offset-4">
            @using (Html.BeginForm("Login", "Usuario", FormMethod.Post))
            {
                <div class="panel panel-primary">
                    <div class="panel-heading"><i class="fa fa-lock"></i> Acesso Restrito</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <label>C.P.F</label>
                                @Html.TextBoxFor(m => m.login, new { @name = "txLogin", @class = "form-control", @onkeyup = "mascara(this, mcpf);", @maxlength = "14" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Senha</label>
                                @Html.PasswordFor(m => m.senha, new { @name = "txSenha", @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-12 topRow">
                            
                                @Session["erroLogin"]
                            
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-md-2">
                                <input type="submit" class="btn btn-primary" value="Entrar" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>