Sl_Processo/Sl_Processo/Controllers/ParticipanteController.cs
using Sl_Processo.Filters;
using Sl_Processo.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sl_Processo.Controllers
{
    [Autenticacao]
    public class ParticipanteController : Controller
    {
        EmpresaParticipanteRepositorio rParticipante = new EmpresaParticipanteRepositorio();
        // GET: Participante
        public ActionResult Index(string letra="A")
        {
            return View(rParticipante.BuscarTodos(letra));
        }
    }
}

Sl_Processo/Sl_Processo/Views/Participante/Index.cshtml
@model IEnumerable<Sl_Processo.Models.ValueObjects.ParticipanteVO>

@{
    ViewBag.Title = "Lista Empresas";
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}
<link href="~/Content/datatable1/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/datatable1/datatables.min.css" rel="stylesheet" />
<style>
    body {
        font-size: .98em !important;
    }
</style>
<br />
<input type="button" value="voltar" onClick="history.go(-1)" class="btn btn-primary"> 

<h3>Lista de Fornecedores Participantes em Processos de Licitação</h3>
<hr />
    <label class="control-label">Selecione...</label>
<nav class="text-center">
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li>@Html.ActionLink("A", "Index", "Participante", new { letra = "A" }, null)</li>
        <li>@Html.ActionLink("B", "Index", "Participante", new { letra = "B" }, null)</li>
        <li>@Html.ActionLink("C", "Index", "Participante", new { letra = "C" }, null)</li>
        <li>@Html.ActionLink("D", "Index", "Participante", new { letra = "D" }, null)</li>
        <li>@Html.ActionLink("E", "Index", "Participante", new { letra = "E" }, null)</li>
        <li>@Html.ActionLink("F", "Index", "Participante", new { letra = "F" }, null)</li>
        <li>@Html.ActionLink("G", "Index", "Participante", new { letra = "G" }, null)</li>
        <li>@Html.ActionLink("H", "Index", "Participante", new { letra = "H" }, null)</li>
        <li>@Html.ActionLink("I", "Index", "Participante", new { letra = "I" }, null)</li>
        <li>@Html.ActionLink("J", "Index", "Participante", new { letra = "J" }, null)</li>
        <li>@Html.ActionLink("K", "Index", "Participante", new { letra = "K" }, null)</li>
        <li>@Html.ActionLink("L", "Index", "Participante", new { letra = "L" }, null)</li>
        <li>@Html.ActionLink("M", "Index", "Participante", new { letra = "M" }, null)</li>
        <li>@Html.ActionLink("N", "Index", "Participante", new { letra = "N" }, null)</li>
        <li>@Html.ActionLink("O", "Index", "Participante", new { letra = "O" }, null)</li>
        <li>@Html.ActionLink("P", "Index", "Participante", new { letra = "P" }, null)</li>
        <li>@Html.ActionLink("Q", "Index", "Participante", new { letra = "Q" }, null)</li>
        <li>@Html.ActionLink("R", "Index", "Participante", new { letra = "R" }, null)</li>
        <li>@Html.ActionLink("S", "Index", "Participante", new { letra = "S" }, null)</li>
        <li>@Html.ActionLink("T", "Index", "Participante", new { letra = "T" }, null)</li>
        <li>@Html.ActionLink("U", "Index", "Participante", new { letra = "U" }, null)</li>
        <li>@Html.ActionLink("V", "Index", "Participante", new { letra = "V" }, null)</li>
        <li>@Html.ActionLink("W", "Index", "Participante", new { letra = "W" }, null)</li>
        <li>@Html.ActionLink("X", "Index", "Participante", new { letra = "X" }, null)</li>
        <li>@Html.ActionLink("Y", "Index", "Participante", new { letra = "Y" }, null)</li>
        <li>@Html.ActionLink("Z", "Index", "Participante", new { letra = "Z" }, null)</li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th style="display: none">@Html.DisplayNameFor(model => model.CodEmpresaParticipante)</th>
            <th><label>CNPJ</label></th>
            <th><label>Razão Social</label></th>
            <th><label>Data de Cadastro</label></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="display: none">@Html.DisplayFor(modelItem => item.CodEmpresaParticipante)</td>
                <td><a href="@Url.Content("~/Processo/ProcessosDoParticipante?codParticipante="+item.CodEmpresaParticipante)" data-toggle="tooltip" title="lista de processos participante" data-placement="right" class="btn btn-default btn-sm"><i class="fa fa-list"></i>&nbsp;@item.CnpjParticipante</a></td>
                <td>@Html.DisplayFor(modelItem => item.RazaoSocialParticipante)</td>
                <td>@Html.DisplayFor(modelItem => item.DataCadastro)</td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {

    @Scripts.Render("~/bundles/datatable1")

    <script>
        
    </script>

    <script>
        $(document).ready(function () {
            $('#example').DataTable({
                "oLanguage": {
                    "sEmptyTable": "Nenhum registro encontrado",
                    "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                    "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sInfoThousands": ".",
                    "sLengthMenu": "_MENU_ resultados por página",
                    "sLoadingRecords": "Carregando...",
                    "sProcessing": "Processando...",
                    "sZeroRecords": "Nenhum registro encontrado",
                    "sSearch": "Pesquisar nesta tabela",
                    "oPaginate": {
                        "sNext": "Próximo",
                        "sPrevious": "Anterior",
                        "sFirst": "Primeiro",
                        "sLast": "Último"
                    }
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            }); $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })
        })
    </script>
}